### PR TITLE
Issue #21: fix incorrect remaining bolus time.

### PR DESCRIPTION
**Pull request by jotomo**
diabetic.happ.integration.openaps.IOB#iobCalc used a hardcoded value,
rather than the one configured and passed to the method (parm dia).

### CODE REVIEW

**Comment by timomer** [comment]
Hey jotomo,

IOB code is taken direct from the OpenAPS project, you can see their files here: https://github.com/openaps/oref0/tree/dev/lib/iob

I have converted their code for Android and added it all in one file, you can see the lines you changed here in their code: https://github.com/openaps/oref0/blob/dev/lib/iob/calculate.js#L3

I do my best to keep the code "as is" and only make adjustments when needed for HAPP, for example how objects are passed.

Would you mind flagging this to them for feedback, they will be able to provide more details as to why this is set as it is. I'm a good few versions behind oref0 releases, when I catch up next I can bring this up then - but will be in a month or so.

**Comment by jotomo** [comment]
Hm, but there are differences in your code compared to oref0:
- oref0 doesn't compute the _minLeft_ value, which is a simplifications AFAIK that only subtracts the time passed since bolus from the duration given in the settings. Wouldn't it be simpler to calculate that value at https://github.com/timomer/HAPP/blob/master/app/src/main/java/com/hypodiabetic/happ/Objects/Treatments.java#L130 (or call a new method there). That would align the code with oref0.
- oref0 uses the _dia_ parameter to calculate the _diaratio_ value, which in turn is used to calculate the _minAgo_ variable. Your code does **not** use the _diaratio_ in the latter calulation and thus ignores the _dia_ argument in the calculation entirely.

**Comment by timomer** [comment]
Hey jotomo, I see what you mean, this is related to #21 that is HAPP code.

I think there are two things to action here...
1. fix the HAPP code for minsLeft, in Dev I am in the process of dropping the treatment object and moving to Bolus and TempBasal objects - ill review #21 and apply the required fix. Your suggestion looks good, ill read more into this. 
2. Why in oref0 is this hard coded? Is this a bug or expected?

Ill leave this open to track progress, feel free to add any more comments.

**Comment by jotomo** [comment]
I think the hardcoded values in oref0 are correct. I know that Humalog has a duration of 3 hours for most people, being most efficient from 60m to 90m, thus having the peak at 75m. oref0 factors the _dia_ value into _minutes_. Minutes aren't real minutes anymore, but adjusted through _dia_ to be comparable with the hardcoded values:

```
var minAgo = diaratio * (time-bolusTime) / 1000 / 60;
```

e.g.
Time since bolus: 60m
dia value: 6.0h
diaRatio = 3.0 / dia => 0.5
minAgo = 60m \* 0.5 => 30m

You could also say _minAgo_ is normalized towards that model :-)

**Comment by jotomo** [comment]
Btw. Android Studio can detect a lot of potential problems by looking at the code. The _diaratio_ variable for example is marked as _Never used_ and which made me look at this in more detail. I like to run _Analyze -> Inspect code_ from time to time. Esp. reported issues in the _Proable bugs_ category are interesting to find issues and also to simplify some constructs :-)

**Comment by timomer** [comment]
Thanks jotomo, I do need to look at this in more detail.

with oref0, agree that the hard coded values should be ok, but as we ask the user for their dia why is it hard coded? These are the questions I want to ask and will do so when I refresh the oref0 code

**Comment by jotomo** [comment]
I played around a bit and pushed a new commit that aligns the java version with what oref0 does, as well as fixing the _bolus time remaining_ display as mentioned in #21.

**Comment by timomer** [comment]
Thanks Jotomo,

IOB - I see what you mean with diaratio variable was not in use, I though this just needed to be cleaned up but checking oref0 I can see this is a mistake I have made.

Treatments - I have moved this code to the new Bolus Object

This is live in Dev now, will track any comments in #21 

Thanks again for your help!

**Pull request closed without merging**
